server:  
      port: 9090 
      session-timeout: 30  
      tomcat.max-threads: 0  
      tomcat.uri-encoding: UTF-8  

logging:
  level: 
   com.wym.springboot01.dao: info   #显示SQL语句



spring:     
    datasource:
        name: springboot01db1
        url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf8&useSSL=true
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20 
  